export const API_CONSTANTS = {
  ANALYTICS_CUTOFF_DAYS: 30,
  MAX_PAGINATION_LIMIT: 100,
  DEFAULT_PAGINATION_LIMIT: 20,
  RATE_LIMIT_SHORTEN_MAX_REQUESTS: 10,
  RATE_LIMIT_REPORT_MAX_REQUESTS: 5,
  RATE_LIMIT_WINDOW_MS: 60000,
  MAX_SLUG_GENERATION_ATTEMPTS: 10,
};

export const POSTGRES_ERROR_CODES = {
  UNIQUE_VIOLATION: "23505",
};
